FROM node:14.18-slim As development

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install --only=development

COPY . .

RUN yarn run build

FROM node:14.18-slim as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

ARG INFURA_KEY
ENV INFURA_KEY=${INFURA_KEY}

ARG MONGO_URI
ENV MONGO_URI=${MONGO_URI}

ARG OPEN_SEA_API_KEY
ENV OPEN_SEA_API_KEY=${OPEN_SEA_API_KEY}

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install --only=production

ENV INFURA_KEY=$INFURA_KEY

ENV MONGO_URI=$MONGO_URI

ENV OPEN_SEA_API_KEY=$OPEN_SEA_API_KEY

ENV GCP_PROJECT_ID=wallettracker-328605

ENV SERVER_MODE=worker

ENV NUMBER_OF_UPDATES=4

ENV PORT=8080

COPY . .

COPY --from=development /usr/src/app/dist ./dist

EXPOSE 8080

CMD ["yarn", "start:prod"]