FROM node:14.18-slim As development

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install --only=development

COPY . .

RUN yarn run build

FROM node:14.18-slim as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install --only=production

ENV INFURA_KEY=f01061b0166e483cb1799669bba2689e

ENV MONGO_URI=mongodb+srv://anthony:dbs123@cluster0.csy6z.mongodb.net/wallet-tracker-stg?retryWrites=true&w=majority

ENV GCP_PROJECT_ID=wallettracker-328605

ENV PORT=8080

ENV DCL_STATS_URL=https://cdn-data.decentraland.org

COPY . .

COPY --from=development /usr/src/app/dist ./dist

EXPOSE 8080

EXPOSE 8088

CMD ["yarn", "start:prod"]