import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { ThemeProvider } from '@mui/material/styles'
import { theme } from '../theme'
import Head from 'next/head'
import { wrapper } from '../store'
import { AuthContextProvider } from '../contexts/AuthContext'
import Web3 from 'web3'
import { Web3ReactProvider } from '@web3-react/core'
import GlobalSnackbar from '../components/GlobalSnackBar'

function getLibrary(provider: any) {
  return new Web3(provider)
}

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Web3ReactProvider getLibrary={getLibrary}>
      <AuthContextProvider>
        <ThemeProvider theme={theme}>
          <Head>
            <title>FAMJ Basketball</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          <Component {...pageProps} />
          <GlobalSnackbar />
        </ThemeProvider>
      </AuthContextProvider>
    </Web3ReactProvider>
  )
}

export default wrapper.withRedux(MyApp)
